// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID
	Name      string
	Type      string
	Currency  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AccountBalance struct {
	AccountID       pgtype.UUID
	AccountName     string
	AccountType     string
	AccountCurrency string
	BalanceMinor    interface{}
}

type LedgerEntry struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	AccountID     pgtype.UUID
	AmountMinor   int64
	Currency      string
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID             pgtype.UUID
	IdempotencyKey string
	Description    pgtype.Text
	Source         string
	PostedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}
