// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
  transaction_id,
  account_id,
  amount_minor,
  currency
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, transaction_id, account_id, amount_minor, currency, created_at
`

type CreateLedgerEntryParams struct {
	TransactionID pgtype.UUID
	AccountID     pgtype.UUID
	AmountMinor   int64
	Currency      string
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.AmountMinor,
		arg.Currency,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  idempotency_key,
  description,
  source,
  posted_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, idempotency_key, description, source, posted_at, created_at
`

type CreateTransactionParams struct {
	IdempotencyKey string
	Description    pgtype.Text
	Source         string
	PostedAt       pgtype.Timestamptz
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.IdempotencyKey,
		arg.Description,
		arg.Source,
		arg.PostedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Source,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, idempotency_key, description, source, posted_at, created_at FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Source,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, idempotency_key, description, source, posted_at, created_at FROM transactions
WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Description,
		&i.Source,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, transaction_id, account_id, amount_minor, currency, created_at FROM ledger_entries
WHERE transaction_id = $1
ORDER BY amount_minor DESC
`

func (q *Queries) ListLedgerEntries(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, idempotency_key, description, source, posted_at, created_at FROM transactions
ORDER BY posted_at DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Description,
			&i.Source,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
